export interface Recipe {
  id: string;
  title: string;
  time: string;
  diff: string;
  tag: string;
  productId: string;
  color: string;
  img: string;
  intro?: string;
  servings?: number;
  ingredients?: string[];
  steps?: string[];
  tips?: string;
}

export const RECIPES: Recipe[] = [
  // ── Fior di Funghi squeeze ────────────────────────────────────
  {
    id: "risotto-porcini",
    title: "Risotto cremoso al fungo",
    time: "25 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "ffps",
    color: "#D4FF3C",
    img: "/images/ricette/risotto-porcini.png",
    intro: "Un risotto avvolgente che in 25 minuti porta il bosco trentino direttamente in tavola. Il segreto? Una bella pressata di Porcini e Speck a fine cottura.",
    servings: 2,
    ingredients: [
      "160g riso Carnaroli",
      "1 squeeze (60g) Fior di Funghi Porcini e Speck",
      "600ml brodo vegetale caldo",
      "1 scalogno tritato",
      "50ml vino bianco secco",
      "30g burro",
      "30g Parmigiano Reggiano grattugiato",
      "Olio EVO, sale, pepe nero",
    ],
    steps: [
      "Scalda il brodo in un pentolino e tienilo caldo a fiamma bassa.",
      "In una padella larga, soffriggi lo scalogno con un filo d'olio EVO per 2 minuti a fuoco medio.",
      "Aggiungi il riso e tostalo 1 minuto rimestando finché i chicchi diventano traslucidi.",
      "Sfuma con il vino bianco e mescola finché evaporato.",
      "Aggiungi il brodo un mestolo alla volta, rimestando continuamente e aspettando che venga assorbito prima di aggiungere il successivo.",
      "A 3 minuti dalla cottura (circa 16 minuti totali), aggiungi 40g di Porcini e Speck al riso e mescola bene.",
      "Togli dal fuoco, manteca con burro e Parmigiano. Regola di sale e pepe.",
      "Impiatta e aggiungi un altro giro di Fior di Funghi in superficie. Servi subito.",
    ],
    tips: "Per un risotto ancora più ricco, aggiungi un cucchiaio di mascarpone durante la mantecatura.",
  },
  {
    id: "burger-gourmet",
    title: "Burger gourmet con fungo",
    time: "15 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "ffps",
    color: "#F2C200",
    img: "/images/ricette/panino-bbq.png",
    intro: "Il classico burger elevato al bosco. Una pressata di Porcini e Speck trasforma un hamburger ordinario in un'esperienza gourmet.",
    servings: 2,
    ingredients: [
      "2 burger bun brioche",
      "2 hamburger (200g cad.) di manzo macinato",
      "2 squeeze (40g) Fior di Funghi Porcini e Speck",
      "2 fette Emmental o Gruyère",
      "Insalata iceberg, pomodoro a fette",
      "Maionese, senape",
      "Sale, pepe",
    ],
    steps: [
      "Scalda la piastra o padella in ghisa a fuoco alto.",
      "Condisci i burger con sale e pepe, cuoci 3 minuti per lato per una cottura media.",
      "Nell'ultimo minuto, adagia il formaggio sopra e lascia sciogliere.",
      "Tosta i panini tagliati sulla piastra per 30 secondi.",
      "Spalma la maionese sul pane inferiore, adagia il burger.",
      "Squeeze generoso di Porcini e Speck direttamente sopra la carne.",
      "Chiudi con insalata, pomodoro e pane superiore. Servi subito.",
    ],
    tips: "Prova a mescolare Porcini e Speck con maionese per una salsa burger del bosco pronta all'uso.",
  },
  {
    id: "bruschette",
    title: "Bruschette autunnali",
    time: "5 min",
    diff: "Facilissima",
    tag: "Fior di Funghi",
    productId: "ffps",
    color: "#E63B1E",
    img: "/images/ricette/risotto-porcini.png",
    intro: "Cinque minuti. Pane, squeeze, cena. Le bruschette più veloci e saporite che tu abbia mai fatto.",
    servings: 4,
    ingredients: [
      "4 fette di pane casereccio toscano o di Altamura",
      "2 squeeze (80g) Fior di Funghi Porcini e Speck",
      "1 spicchio d'aglio",
      "Olio EVO di qualità",
      "Timo fresco o rosmarino",
      "Sale grosso",
    ],
    steps: [
      "Tosta il pane sotto il grill o in padella senza olio finché è dorato e croccante.",
      "Strofina subito lo spicchio d'aglio su un lato del pane ancora caldo.",
      "Aggiungi un filo d'olio EVO.",
      "Squeeze generoso di Porcini e Speck su ogni fetta.",
      "Aggiungi qualche fogliolina di timo e un pizzico di sale grosso.",
      "Servi immediatamente — le bruschette aspettano il commensale, non il contrario.",
    ],
    tips: "Aggiungi una fettina di pecorino stagionato sopra e passa 30 secondi sotto il grill per una versione ancora più ricca.",
  },
  {
    id: "uova-tartufo",
    title: "Uova strapazzate al tartufo",
    time: "8 min",
    diff: "Facilissima",
    tag: "Fior di Funghi",
    productId: "fftap",
    color: "#2E4FE8",
    img: "/images/ricette/tartufo-pecorino.png",
    intro: "La colazione degli chef. Uova strapazzate morbide, quasi cremose, con il profumo inconfondibile del tartufo e la sapidità del pecorino.",
    servings: 2,
    ingredients: [
      "4 uova freschissime",
      "1 squeeze (30g) Fior di Funghi Tartufo e Pecorino",
      "20g burro",
      "1 cucchiaio panna fresca",
      "Sale, pepe bianco",
      "Erba cipollina per guarnire",
      "Pane tostato per servire",
    ],
    steps: [
      "Rompi le uova in una ciotola, aggiungi la panna e un pizzico di sale. Sbatti leggermente con una forchetta — non troppo.",
      "Metti il burro in una padella antiaderente a fuoco MOLTO basso.",
      "Quando il burro è sciolto, versa le uova. Non mescolare subito.",
      "Quando cominciano a solidificarsi ai bordi, rimesta lentamente con una spatola di silicone dal bordo verso il centro.",
      "Togli dal fuoco PRIMA che sembrino cotte — continuano a cuocere nella padella calda.",
      "Aggiungi lo squeeze di Tartufo e Pecorino fuori dal fuoco e mescola delicatamente.",
      "Impiatta su pane tostato, aggiungi pepe bianco ed erba cipollina.",
    ],
    tips: "Il segreto delle uova strapazzate perfette è la pazienza e il fuoco basso. Non fretta.",
  },
  {
    id: "toast-gourmet",
    title: "Toast gourmet al tartufo",
    time: "5 min",
    diff: "Facilissima",
    tag: "Fior di Funghi",
    productId: "fftap",
    color: "#F5EFE0",
    img: "/images/ricette/tartufo-pecorino.png",
    intro: "Il toast non era mai stato così elegante. Tre ingredienti, cinque minuti, risultato da ristorante.",
    servings: 1,
    ingredients: [
      "2 fette pane in cassetta o pan brioche",
      "1 squeeze (25g) Fior di Funghi Tartufo e Pecorino",
      "2 fette prosciutto crudo di Parma",
      "1 fetta Fontina o Gruyère",
      "Burro per la padella",
    ],
    steps: [
      "Spalma Tartufo e Pecorino su una delle fette di pane.",
      "Adagia prosciutto crudo e formaggio sopra.",
      "Chiudi con l'altra fetta.",
      "Scalda una padella con un velo di burro a fuoco medio.",
      "Cuoci il toast 2 minuti per lato premendo leggermente con una spatola, finché dorato e il formaggio è sciolto.",
      "Taglia in diagonale e servi subito.",
    ],
  },
  {
    id: "tagliolini",
    title: "Tagliolini al tartufo e pecorino",
    time: "10 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "fftap",
    color: "#D4FF3C",
    img: "/images/ricette/tartufo-pecorino.png",
    intro: "La pasta più lussuosa in 10 minuti. Tagliolini all'uovo, burro, squeeze di tartufo. Fine.",
    servings: 2,
    ingredients: [
      "200g tagliolini all'uovo freschi",
      "2 squeeze (60g) Fior di Funghi Tartufo e Pecorino",
      "40g burro",
      "30g Parmigiano Reggiano grattugiato",
      "Acqua di cottura della pasta",
      "Pepe nero macinato fresco",
    ],
    steps: [
      "Cuoci i tagliolini in abbondante acqua salata — freschi: 2–3 minuti.",
      "Mentre la pasta cuoce, sciogli il burro in una padella larga a fuoco bassissimo.",
      "Scola i tagliolini al dente, conservando una tazza di acqua di cottura.",
      "Trasferisci la pasta nella padella con il burro. Aggiungi 2–3 cucchiai di acqua di cottura.",
      "A fuoco spento, aggiungi Tartufo e Pecorino e mescola energicamente finché cremoso.",
      "Aggiungi Parmigiano e ancora un po' di acqua di cottura se serve.",
      "Impiatta e finisci con pepe nero generoso.",
    ],
    tips: "A fuoco SPENTO per aggiungere lo squeeze. Il calore diretto rovinerebbe i profumi del tartufo.",
  },
  {
    id: "costine",
    title: "Costine BBQ al fungo",
    time: "60 min",
    diff: "Media",
    tag: "Fior di Funghi",
    productId: "ffpab",
    color: "#E63B1E",
    img: "/images/ricette/panino-bbq.png",
    intro: "Le costine che tutti chiedono la ricetta. La salsa Paprika e BBQ caramellizza sul maiale in forno per un risultato irresistibile.",
    servings: 4,
    ingredients: [
      "1kg costine di maiale",
      "3 squeeze (90g) Fior di Funghi Paprika e BBQ",
      "2 cucchiai miele",
      "1 cucchiaio salsa Worcestershire",
      "1 cucchiaino paprika dolce",
      "Sale, pepe",
    ],
    steps: [
      "Preriscalda il forno a 160°C.",
      "Prepara la marinata: mescola Paprika e BBQ con miele, Worcestershire e paprika dolce.",
      "Condisci le costine con sale e pepe, poi spalma metà marinata su entrambi i lati.",
      "Avvolgi le costine in carta stagnola e inforna per 45 minuti.",
      "Apri la stagnola, spennella con il resto della marinata.",
      "Alza il forno a 220°C e cuoci scoperto altri 10–15 minuti finché la superficie caramellizza.",
      "Lascia riposare 5 minuti prima di tagliare. Servi con pane rustico.",
    ],
  },
  {
    id: "patatine",
    title: "Patatine al forno paprika",
    time: "35 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "ffpab",
    color: "#F2C200",
    img: "/images/ricette/panino-bbq.png",
    intro: "Patatine croccanti fuori, morbide dentro, con la magia del fungo affumicato.",
    servings: 4,
    ingredients: [
      "800g patate a pasta gialla",
      "2 squeeze (60g) Fior di Funghi Paprika e BBQ",
      "3 cucchiai olio EVO",
      "Rosmarino fresco",
      "Sale grosso, pepe",
    ],
    steps: [
      "Preriscalda il forno a 200°C ventilato.",
      "Lava le patate e tagliale a spicchi senza sbucciarle.",
      "In una ciotola grande, mescola le patate con olio EVO, sale e Paprika e BBQ. Ricopri ogni spicchio uniformemente.",
      "Disponi su teglia foderata con carta forno, senza sovrapporle.",
      "Inforna 30–35 minuti, girandole a metà cottura.",
      "Aggiungi rosmarino fresco negli ultimi 5 minuti.",
      "Servi calde con uno squeeze extra a lato come salsa dipping.",
    ],
  },
  {
    id: "hotdog",
    title: "Hot dog gourmet del bosco",
    time: "10 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "ffpab",
    color: "#D4FF3C",
    img: "/images/ricette/panino-bbq.png",
    intro: "L'hot dog che non ti aspetti. Il fungo BBQ sostituisce (e supera) qualsiasi salsa industriale.",
    servings: 4,
    ingredients: [
      "4 wurstel di qualità (maiale o manzo)",
      "4 panini hot dog",
      "2 squeeze (60g) Fior di Funghi Paprika e BBQ",
      "Maionese",
      "Senape",
      "Cipolla fresca a rondelle sottili",
      "Cetriolini sottaceto",
    ],
    steps: [
      "Scalda i wurstel in acqua bollente o su griglia per 5 minuti.",
      "Tosta leggermente i panini tagliati.",
      "Spalma maionese e senape su entrambi i lati del panino.",
      "Inserisci il wurstel e aggiungi squeeze di Paprika e BBQ direttamente sopra.",
      "Guarnisci con cipolla fresca e cetriolini.",
      "Servi subito.",
    ],
  },
  {
    id: "salmone",
    title: "Salmone alla brace teriyaki",
    time: "20 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "fft",
    color: "#2E4FE8",
    img: "/images/ricette/teriyaki-salmone.png",
    intro: "Salmone glassato con la salsa fusion del bosco. Fuori caramellizzato, dentro succoso.",
    servings: 2,
    ingredients: [
      "2 tranci salmone (250g cad.) con pelle",
      "3 squeeze (90g) Fior di Funghi Teriyaki e Zenzero",
      "1 cucchiaio olio di sesamo",
      "Semi di sesamo tostati",
      "Cipollotto a fettine",
      "Riso bianco per servire",
    ],
    steps: [
      "Marina il salmone in 2 squeeze di Teriyaki e Zenzero per 15 minuti.",
      "Scalda una padella antiaderente a fuoco medio-alto con olio di sesamo.",
      "Cuoci il salmone lato pelle 4 minuti, poi gira e cuoci altri 3 minuti.",
      "Nell'ultimo minuto aggiungi ancora un po' di salsa teriyaki sopra e lascia caramellizzare.",
      "Impiatta su riso bianco, guarnisci con sesamo e cipollotto.",
      "Aggiungi un ultimo squeeze di Teriyaki e Zenzero a crudo prima di servire.",
    ],
  },
  {
    id: "bowl-pollo",
    title: "Bowl di pollo teriyaki",
    time: "25 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "fft",
    color: "#F5EFE0",
    img: "/images/ricette/teriyaki-salmone.png",
    intro: "La bowl che metti in Instagram. Colorata, bilanciata, saporita. E il bosco c'è dentro.",
    servings: 2,
    ingredients: [
      "2 petti di pollo",
      "2 squeeze (60g) Fior di Funghi Teriyaki e Zenzero",
      "200g riso basmati",
      "1 avocado a fette",
      "Edamame sgusciati",
      "Carote julienne",
      "Sesamo, cipollotto, coriandolo",
    ],
    steps: [
      "Marina il pollo in Teriyaki e Zenzero per almeno 15 minuti (o fino a 24h in frigo).",
      "Cuoci il riso basmati e tienilo in caldo.",
      "Cuoci il pollo in padella 6 minuti per lato a fuoco medio, glassando con la marinata avanzata.",
      "Fai riposare 3 minuti, poi affetta.",
      "Assembla la bowl: riso alla base, pollo al centro, avocado, edamame e carote intorno.",
      "Finisci con sesamo, cipollotto, coriandolo e un ultimo squeeze di Teriyaki direttamente.",
    ],
  },
  {
    id: "wok-verdure",
    title: "Wok di verdure fusion",
    time: "15 min",
    diff: "Facile",
    tag: "Fior di Funghi",
    productId: "fft",
    color: "#D4FF3C",
    img: "/images/ricette/teriyaki-salmone.png",
    intro: "Verdure saltate in wok con la salsa più inaspettata: fungo, teriyaki, zenzero. Pronto in 15 minuti.",
    servings: 2,
    ingredients: [
      "300g mix verdure (peperone, zucchina, broccoli, carota)",
      "2 squeeze (60g) Fior di Funghi Teriyaki e Zenzero",
      "2 cucchiai olio di arachidi",
      "1 spicchio aglio",
      "Noodles o riso per servire",
    ],
    steps: [
      "Taglia tutte le verdure in pezzi della stessa dimensione per cottura uniforme.",
      "Scalda il wok (o padella larga antiaderente) a fuoco altissimo con olio di arachidi.",
      "Aggiungi l'aglio tritato e soffriggi 30 secondi.",
      "Aggiungi le verdure più dure (carota, broccoli) per prime, poi le più morbide.",
      "Salta continuamente per 5–6 minuti — le verdure devono restare croccanti.",
      "Abbassa la fiamma, aggiungi Teriyaki e Zenzero e mescola bene per 1 minuto.",
      "Servi subito su noodles o riso bianco.",
    ],
  },

  // ── Funghi Secchi ─────────────────────────────────────────────
  {
    id: "risotto-secchi",
    title: "Risotto ai Porcini Secchi",
    time: "35 min",
    diff: "Facile",
    tag: "Funghi Secchi",
    productId: "psec",
    color: "#D9A547",
    img: "/images/ricette/risotto-secchi.png",
    intro: "Il risotto della tradizione italiana. Con i porcini secchi Dial Funghi, ogni chicco assorbe l'aroma intenso del bosco trentino.",
    servings: 4,
    ingredients: [
      "320g riso Carnaroli",
      "30g Porcini Secchi Dial Funghi",
      "1l brodo di verdure caldo",
      "1 cipolla piccola",
      "100ml vino bianco secco",
      "50g burro",
      "60g Parmigiano Reggiano",
      "Olio EVO, sale, pepe",
      "Prezzemolo fresco",
    ],
    steps: [
      "Ammolla i porcini secchi in 200ml di acqua tiepida per 20 minuti. Conserva l'acqua di ammollo filtrata.",
      "Soffriggi la cipolla tritata in olio e metà burro per 3 minuti.",
      "Aggiungi il riso, tostalo 1 minuto rimestando.",
      "Sfuma con vino bianco, poi aggiungi l'acqua di ammollo filtrata.",
      "Aggiungi i porcini strizzati e tritati grossolanamente.",
      "Continua con il brodo caldo, un mestolo alla volta, per circa 18 minuti.",
      "Manteca a fuoco spento con burro e Parmigiano.",
      "Aggiungi prezzemolo tritato, regola di sale. Lascia riposare 2 minuti coperto prima di servire.",
    ],
    tips: "L'acqua di ammollo è oro: filtrarla con un colino fine e usarla nel risotto raddoppia il sapore.",
  },
  {
    id: "sugo-porcini",
    title: "Sugo ai Porcini per Pasta",
    time: "20 min",
    diff: "Facile",
    tag: "Funghi Secchi",
    productId: "psec",
    color: "#A66B3D",
    img: "/images/ricette/sugo-porcini.png",
    intro: "Il sugo del lunedì e della domenica. Veloce, profondo, con quel sapore di bosco che le salse industriali non raggiungeranno mai.",
    servings: 4,
    ingredients: [
      "20g Porcini Secchi Dial Funghi",
      "400g spaghetti o pappardelle",
      "400g pomodori pelati",
      "1 spicchio aglio",
      "Olio EVO",
      "Vino bianco 50ml",
      "Prezzemolo, sale, pepe",
    ],
    steps: [
      "Ammolla i porcini in acqua tiepida per 20 minuti. Filtra e conserva l'acqua.",
      "Soffriggi l'aglio in olio per 1 minuto, poi aggiungi i porcini strizzati.",
      "Cuoci 2 minuti, sfuma con vino bianco.",
      "Aggiungi pomodori pelati e l'acqua di ammollo. Regola di sale.",
      "Cuoci a fuoco medio 15 minuti finché il sugo si addensa.",
      "Cuoci la pasta, scolala al dente, trasferiscila nella padella con il sugo.",
      "Manteca a fuoco alto 1 minuto aggiungendo acqua di cottura se serve. Pepe e prezzemolo.",
    ],
  },
  {
    id: "trifolato",
    title: "Trifolato di Funghi Misti",
    time: "15 min",
    diff: "Facile",
    tag: "Funghi Secchi",
    productId: "finf",
    color: "#D4FF3C",
    img: "/images/ricette/trifolato.png",
    intro: "Contorno semplice e nobile. I finferli secchi reidratati saltati in padella con aglio e prezzemolo — una preparazione che esalta ogni sapore.",
    servings: 4,
    ingredients: [
      "25g Finferli Secchi Dial Funghi",
      "2 spicchi aglio",
      "50ml olio EVO",
      "Prezzemolo fresco abbondante",
      "Sale, pepe nero",
      "Peperoncino (opzionale)",
    ],
    steps: [
      "Ammolla i finferli in acqua tiepida 15 minuti, poi strizzali bene.",
      "Soffriggi l'aglio in olio a fuoco medio finché dorato, poi rimuovilo.",
      "Aggiungi i finferli e cuoci a fuoco medio-alto rimestando, 5–6 minuti.",
      "Regola di sale e pepe. Aggiungi un pizzico di peperoncino se gradito.",
      "A fuoco spento, aggiungi prezzemolo abbondante tritato.",
      "Usa come contorno, condimento per bruschette, o sopra tagliatelle al burro.",
    ],
  },
  {
    id: "zuppa-bosco",
    title: "Zuppa del Bosco",
    time: "40 min",
    diff: "Facile",
    tag: "Funghi Secchi",
    productId: "psec",
    color: "#8B5A2B",
    img: "/images/ricette/zuppa-bosco.png",
    intro: "La zuppa che scalda. Con i porcini secchi e legumi, è un piatto completo che profuma di autunno trentino.",
    servings: 4,
    ingredients: [
      "25g Porcini Secchi Dial Funghi",
      "400g fagioli borlotti (lessi o in scatola)",
      "2 patate medie a cubetti",
      "1 carota, 1 gambo sedano, 1 cipolla",
      "1l brodo vegetale",
      "400g pomodori pelati",
      "Olio EVO, rosmarino, alloro",
      "Sale, pepe",
      "Pane rustico per servire",
    ],
    steps: [
      "Ammolla i porcini 20 minuti in acqua tiepida. Conserva l'acqua filtrata.",
      "Soffriggi cipolla, carota e sedano in olio per 5 minuti.",
      "Aggiungi patate, porcini e rosmarino. Cuoci 2 minuti.",
      "Aggiungi pomodori, brodo e acqua di ammollo. Porta a ebollizione.",
      "Cuoci 20 minuti a fuoco medio. Aggiungi i fagioli e cuoci altri 10 minuti.",
      "Regola di sale e pepe.",
      "Servi con pane rustico tostato strofinato con aglio e un filo d'olio EVO.",
    ],
  },
  {
    id: "morchelle-uova",
    title: "Morchelle con Uova al Burro",
    time: "12 min",
    diff: "Media",
    tag: "Funghi Secchi",
    productId: "morc",
    color: "#F5EFE0",
    img: "/images/ricette/morchelle-uova.png",
    intro: "Un piatto da grande chef con tre ingredienti. Le morchelle sono tra i funghi più pregiati al mondo — rispettale con semplicità.",
    servings: 2,
    ingredients: [
      "10g Morchelle Secche Dial Funghi",
      "4 uova freschissime",
      "60g burro di qualità",
      "Sherry secco 2 cucchiai",
      "Panna fresca 2 cucchiai",
      "Sale, pepe bianco",
      "Crostini di pane per servire",
    ],
    steps: [
      "Ammolla le morchelle in acqua tiepida per 20 minuti. Strizzale delicatamente e asciugale.",
      "Soffriggi le morchelle in metà burro per 3 minuti a fuoco medio.",
      "Sfuma con sherry e cuoci finché evaporato. Aggiungi panna, sale, pepe.",
      "In altra padella, cuoci le uova all'occhio di bue o strapazzate morbide con il burro restante.",
      "Impiatta le uova, adagia le morchelle sopra con il loro fondo di cottura.",
      "Servi con crostini di pane per raccogliere il sughetto.",
    ],
    tips: "Le morchelle devono essere ben cotte — non consumarle mai crude.",
  },
  {
    id: "ramen-shiitake",
    title: "Ramen allo Shiitake",
    time: "30 min",
    diff: "Media",
    tag: "Funghi Secchi",
    productId: "shit",
    color: "#E63B1E",
    img: "/images/ricette/ramen-shiitake.png",
    intro: "Il ramen fatto in casa con il carattere dello shiitake. Un brodo umami profondo che scalda corpo e spirito.",
    servings: 2,
    ingredients: [
      "20g Shiitake a Fette Dial Funghi",
      "2 porzioni noodles ramen",
      "1l brodo di pollo o dashi",
      "2 cucchiai salsa di soia",
      "1 cucchiaio mirin",
      "2 uova sode marinate",
      "Cipollotto, alga nori, sesamo",
      "Pasta di miso 1 cucchiaio (opzionale)",
    ],
    steps: [
      "Ammolla gli shiitake in 400ml acqua tiepida per 20 minuti. Conserva l'acqua filtrata.",
      "Porta a ebollizione il brodo con l'acqua di ammollo degli shiitake.",
      "Aggiungi salsa di soia, mirin e gli shiitake. Cuoci 10 minuti.",
      "Se usi il miso, scioglilo nel brodo fuori dal fuoco.",
      "Cuoci i noodles separatamente seguendo le istruzioni.",
      "Assembla: noodles nella ciotola, versa il brodo bollente.",
      "Guarnisci con uovo tagliato a metà, cipollotto, alga nori e sesamo.",
    ],
  },

  // ── Polenta ───────────────────────────────────────────────────
  {
    id: "polenta-porcini",
    title: "Polenta Cremosa ai Porcini",
    time: "10 min",
    diff: "Facilissima",
    tag: "Polenta",
    productId: "pol",
    color: "#D9A547",
    img: "/images/ricette/polenta-porcini.png",
    intro: "La polenta veloce che non tradisce. Con i porcini già dentro, in 10 minuti hai un piatto completo e confortante.",
    servings: 4,
    ingredients: [
      "250g Polenta ai Porcini Dial Funghi",
      "1l acqua",
      "1 cucchiaino sale grosso",
      "50g burro",
      "50g Parmigiano Reggiano",
      "Funghi trifolati o salsiccia per servire",
    ],
    steps: [
      "Porta l'acqua salata a ebollizione.",
      "Versa la polenta a pioggia mescolando continuamente con una frusta.",
      "Cuoci 5 minuti rimestando spesso a fuoco medio.",
      "Togli dal fuoco, aggiungi burro e Parmigiano. Mescola fino a cremosa.",
      "Servi subito — la polenta solidifica aspettando.",
      "Accompagna con funghi trifolati, salsiccia o formaggi di montagna.",
    ],
    tips: "Per una polenta più ricca, usa latte al posto di metà acqua.",
  },
  {
    id: "crostini-polenta",
    title: "Crostini di Polenta Fritta",
    time: "20 min",
    diff: "Facile",
    tag: "Polenta",
    productId: "pol",
    color: "#F2C200",
    img: "/images/ricette/crostini-polenta.png",
    intro: "La polenta avanzata si trasforma. Fritta diventa croccante fuori e morbida dentro — perfetta come antipasto o finger food.",
    servings: 6,
    ingredients: [
      "Polenta ai Porcini cotta il giorno prima (250g farina)",
      "Olio di girasole per friggere",
      "Salumi, formaggi, verdure per guarnire",
      "Sale grosso",
    ],
    steps: [
      "Versa la polenta calda in uno stampo rettangolare unto, livella con una spatola.",
      "Lascia raffreddare completamente in frigo per almeno 2 ore (o tutta la notte).",
      "Taglia a rettangoli o triangoli di 1,5cm di spessore.",
      "Scalda abbondante olio a 180°C in padella.",
      "Friggi i crostini 2 minuti per lato finché dorati e croccanti.",
      "Scola su carta assorbente, aggiungi sale grosso.",
      "Servi caldi con salumi, formaggi fondenti o salsina ai funghi.",
    ],
  },
  {
    id: "polenta-cotechino",
    title: "Polenta con Ragù di Funghi",
    time: "45 min",
    diff: "Media",
    tag: "Polenta",
    productId: "pol",
    color: "#E63B1E",
    img: "/images/ricette/polenta-cotechino.png",
    intro: "Il piatto della domenica trentina. Polenta morbida con un ricco ragù di funghi misti — comfort food elevato.",
    servings: 6,
    ingredients: [
      "250g Polenta ai Porcini Dial Funghi",
      "500g funghi freschi misti (champignon, portobello, porcini)",
      "300g macinato di manzo (opzionale)",
      "400g pomodori pelati",
      "1 cipolla, 1 carota, 1 sedano",
      "100ml vino rosso",
      "Olio EVO, rosmarino, alloro",
      "Sale, pepe",
    ],
    steps: [
      "Prepara il soffritto con cipolla, carota e sedano in olio per 5 minuti.",
      "Aggiungi il macinato (se usi) e rosola 5 minuti finché dorato.",
      "Aggiungi i funghi puliti e tagliati, cuoci 5 minuti.",
      "Sfuma con vino rosso, lascia evaporare.",
      "Aggiungi pomodori, rosmarino, alloro. Cuoci a fuoco lento 30 minuti.",
      "Negli ultimi 10 minuti, prepara la polenta come da istruzioni.",
      "Servi la polenta cremosa con il ragù sopra e Parmigiano grattugiato.",
    ],
  },

  // ── Condimenti ────────────────────────────────────────────────
  {
    id: "pasta-grigliata",
    title: "Pasta alla Grigliata di Montagna",
    time: "15 min",
    diff: "Facile",
    tag: "Condimenti",
    productId: "grig",
    color: "#7A4226",
    img: "/images/ricette/pasta-grigliata.png",
    intro: "Una pasta che sa di escursione in quota. Il condimento Grigliata di Montagna trasforma un sugo semplice in qualcosa di memorabile.",
    servings: 4,
    ingredients: [
      "400g rigatoni o penne",
      "2 cucchiaini colmi Grigliata di Montagna Dial Funghi",
      "400g salsiccia fresca (o champignon per versione vegana)",
      "200ml panna fresca",
      "1 spicchio aglio",
      "Olio EVO",
      "Parmigiano, pepe nero",
    ],
    steps: [
      "Cuoci la pasta in abbondante acqua salata.",
      "Soffriggi l'aglio in olio, aggiungi la salsiccia sbriciolata.",
      "Rosola 5 minuti, aggiungi 2 cucchiaini di Grigliata di Montagna.",
      "Aggiungi la panna, cuoci 3 minuti a fuoco basso.",
      "Scola la pasta al dente e uniscila al sugo con un po' di acqua di cottura.",
      "Manteca 1 minuto, regola di sale.",
      "Servi con Parmigiano e pepe nero abbondante.",
    ],
  },
  {
    id: "pollo-condito",
    title: "Petto di Pollo al Condimento Funghi",
    time: "25 min",
    diff: "Facile",
    tag: "Condimenti",
    productId: "papor",
    color: "#D4FF3C",
    img: "/images/ricette/pollo-condito.png",
    intro: "Il petto di pollo non deve essere noioso. Con il Preparato ai Porcini diventa succoso, aromatico e impossibile da dimenticare.",
    servings: 2,
    ingredients: [
      "2 petti di pollo",
      "2 cucchiaini Pasta ai Porcini Dial Funghi",
      "Olio EVO",
      "Aglio, rosmarino",
      "100ml vino bianco",
      "Sale, pepe",
      "Limone per servire",
    ],
    steps: [
      "Mescola il Preparato ai Porcini con olio EVO per formare una pasta.",
      "Spalma la marinata su entrambi i lati del pollo, lascia riposare 10 minuti.",
      "Scalda una padella a fuoco medio-alto con poco olio.",
      "Cuoci il pollo 6 minuti per lato senza muoverlo — per una crosticina dorata.",
      "Sfuma con vino bianco, aggiungi rosmarino e aglio in camicia.",
      "Abbassa la fiamma e cuoci 5 minuti con coperchio.",
      "Lascia riposare 3 minuti prima di tagliare. Servi con limone e verdure grigliate.",
    ],
  },
  {
    id: "verdure-griglio",
    title: "Verdure Grigliate al Bosco",
    time: "20 min",
    diff: "Facile",
    tag: "Condimenti",
    productId: "grig",
    color: "#F5EFE0",
    img: "/images/ricette/verdure-griglio.png",
    intro: "Contorno universale che non annoia mai. Il condimento Grigliata di Montagna esalta ogni verdura con la profondità del fungo essiccato.",
    servings: 4,
    ingredients: [
      "600g mix verdure (zucchine, melanzane, peperoni, cipolla rossa)",
      "2 cucchiaini Grigliata di Montagna Dial Funghi",
      "4 cucchiai olio EVO",
      "Aglio, timo, origano",
      "Sale, pepe",
      "Aceto balsamico (opzionale)",
    ],
    steps: [
      "Taglia le verdure a fette spesse 0,5cm o a metà per le più piccole.",
      "Mescola in ciotola con olio, Grigliata di Montagna, sale e pepe.",
      "Preriscalda la griglia o piastra al massimo.",
      "Griglia ogni verdura finché ha i segni della griglia e è tenera — circa 3 minuti per lato.",
      "Disponi su piatto da portata, aggiungi aglio tritato crudo e erbe fresche.",
      "Un filo d'aceto balsamico finale completa il piatto.",
    ],
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

export function getRecipesByProductId(productId: string): Recipe[] {
  return RECIPES.filter((r) => r.productId === productId);
}
